name = "copycodeai-functions"

# Metti una data recente (oggi va benissimo)
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSION"
id = "dev-SESSION"
preview_id = "dev-SESSION"
